server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          # ?i?u ki?n ?? gateway map endpoint
          predicates:
          - Path=/identity/**
#          filters:
#          - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          # ?i?u ki?n ?? gateway map endpoint
          # Chú ý r?ng không h? có /internal, không export, vì v?y s? không cho g?i post profile ;)
          predicates:
          - Path=/profile/**
          # C?t ?i custom prefix (c?t api là l?y ph?n sau ?? routing)
#          filters:
#          - StripPrefix=2